from collections import deque
cola=deque(["Ana","Carlos"])
cola.append("jorge")
print("Cola actual:", cola)
atendido=cola.popleft()
print(f"se atendio a:{atendido}")
print("cola restante:",cola)
atendido=cola.popleft()
print(f"se atendio a:{atendido}")
print("cola restante:",cola)
